const express = require('express');
const keys = require('./config/keys');
const mongoose = require('mongoose');
const path = require('path');
require('./models/File');
require('./models/User');
require('./models/Entity');

mongoose.connect(keys['MONGO-URI']);

const app = express();
// enable apis to our backend
require('./apis/file_uploader/file_uploader')(app);
require('./apis/news_digester/news_api')(app);

const PORT = process.env.PORT || 5000;
app.listen(PORT, ()=>console.log(`express listening at ${PORT}`));

// load static page generated by React
app.use(express.static(path.join(__dirname, 'client', 'build')));
