const express = require('express');
const path = require('path');
const app = express();

// file upload api
require('./apis/file_uploader/file_uploader')(app);

const PORT = process.env.PORT || 5000;
app.listen(PORT, ()=>console.log(`express listening at ${PORT}`));

// load static page generated by React
app.use(express.static(path.join(__dirname, 'client', 'build')));
